### ISSUE TITLE
Is the bot running correctly?

### ISSUE THREAD

**Issue by mirorauhala** [reactjs/translations.react.dev#196] opened 2022-06-01 07:52 UTC
My PR #191 for adding a new language should have triggered the creation of a new repository last Monday to the reactjs org but it hasn't.

From the readme:

> Once the PR is accepted, the bot will:
> 
> - Create a new repository for you at reactjs/{lang-code}.reactjs.org
> - Add/invite all maintainers listed to a "reactjs.org {language} Translation" team in the reactjs organization
> - Create an issue from [PROGRESS.template.md](https://github.com/reactjs/reactjs.org-translation/blob/main/PROGRESS.template.md) in the new repository to track your translation progress
> 

The Procfile has the scripts automated to run on Mondays at 08:00. 
https://github.com/reactjs/reactjs.org-translation/blob/720817338730965829cfe192ef1bbd4da47b3be5/Procfile#L1

I've already created a repository under my profile, but for the sake of consistency, I would like to migrate it under the reactjs org. Thanks!

**Comment by gaearon** [comment] 2022-06-03 13:57
cc @bvaughn I remember we moved the script out of Nat's Heroku instance but I can't find where we documented the new setup... Do you have access to this?

**Comment by gaearon** [comment] 2022-06-03 14:15
ahhh ok

**Comment by bvaughn** [comment] 2022-06-03 14:16
It's possible the script has since stopped working (maybe a token has expired or something?) Haven't thought about the script in several months.

**Comment by gaearon** [comment] 2022-06-03 14:18
Hmm, is the sync script responsible for granting repo permissions? I'm looking at it now but I think it's only sending PRs. There's something else that's supposed to grant repo permissions. I'll find your post after breakfast..

**Comment by gaearon** [comment] 2022-06-03 14:18
To clarify, the problem isn't with the sync but with creating a fork automatically and updating translation maintainers

**Comment by bvaughn** [comment] 2022-06-03 16:20
I don't remember but I _think_ there may have been a manual step involved. I'd have to re-read my old notes (post)

**Comment by gaearon** [comment] 2023-04-25 18:14
@bvaughn Re-reading your post, it's entirely concerned with translation *content* syncing. All the logic for the *permission* syncing is still in this repo. I presume it was never hooked up to GH Actions, which is why it stopped working the moment Heroku was disconnected.

**Comment by bvaughn** [comment] 2023-04-25 18:16
@gaearon I can believe it. It's been years since I've been involved with this and I don't even have access to my old notes or the post you're talking about.

**Comment by gaearon** [comment] 2023-04-25 18:20
OK that makes sense. Do you remember if there's any reason this repo has permissions set to everyone? I was thinking of moving the syncing script back, but removing permissions for everyone except org admins. So we'd review the maintainer change requests (which are rare), but the script would be public. Does this make sense?

**Comment by bvaughn** [comment] 2023-04-25 18:25
Honestly I don't know. I _thought_ I had setup GH actions for the permissions _specifically_ because that seemed like a security concern. I don't have access to notes (or even the actions or org settings anymore) to confirm that or to jog my memory though, and it's been years.

You probably have more context than I do at this point regarding what makes the most sense.

**Comment by gaearon** [comment] 2023-04-28 01:44
@mirorauhala Apologies for this — our bad. (We were already working on the new site so didn't feel like this was urgent.) We're fixing this soon: https://github.com/reactjs/translations.react.dev/pull/285

**Comment by gaearon** [comment] 2023-04-29 02:54
Fixed by https://github.com/reactjs/translations.react.dev/pull/285.

**Closed by gaearon** 2023-04-29 02:54 UTC

**Comment by gaearon** [comment] 2023-04-29 03:08
https://github.com/reactjs/fi.react.dev/issues/1
